spring.application.name=demo
aws.ses.from-email=<your from email>
aws.ses.admin-email=<your admin email>
aws.ses.smtp.host=<your smtp host>
aws.ses.smtp.port=<your smtp port>
aws.ses.smtp.username=<your smtp user name>
aws.ses.smtp.password=<your smtp password>
logging.level.com.example.demo=INFO
logging.level.com.amazonaws=WARN
