package com.example.demo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Lead")
public class LeadEntity {

	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private String phone;
	@DynamoDBAttribute
	private String desc;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return email;
	}
	public LeadEntity() {
		super();
		// TODO Auto-generated constructor stub
	}
	public LeadEntity(String id, String name, String email, String phone, String desc) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.desc = desc;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
}
